### ISSUE TITLE
-ldl in AM_LDFLAGS breaks building for systems that don't know/use that library

### ISSUE THREAD

**Issue by s-ag** [utelle/wxsqlite3#101]
This bug was introduced in wxsqlite3 4.4.7 and affects eg. building for mingw-w64 on Debian 10.

**Comment by utelle** [comment]
This _"bug"_ was introduced more than 2 years ago, because another user had problems with linking for a Linux system (see issue  #80). So, for you it's a _bug_, for others it's a _solution_.

Obviously, you are cross-compiling for Windows on a Debian system. I have to admit that I hadn't cross-compiling in mind when creating the autoconf/automake build files. I'll try to find a way to support your use case, but it may take a while, because I'm no autoconf/automake expert.

If you happen to be able to provide a solution that works for both use cases, then please let me know. Thanks.

**Comment by utelle** [comment]
Could you please check whether the modification introduced with commit 6714e2196443a36e1a18ff6ad7efc0f1f348cc03 solves your problem? TIA

**Comment by s-ag** [comment]
Perfect.
Thank you very much for the quick response.

**Comment by utelle** [comment]
Thanks for confirming. Closing...
