### ISSUE TITLE
Visual Studio 2022 says wxprec.h is missing

### ISSUE THREAD

**Issue by Qriist** [utelle/wxsqlite3#102]
hey there, I'm having trouble compiling under Visual Studio 2022. It keeps telling me the following file not found error:
![image](https://user-images.githubusercontent.com/26832022/167280636-421fbec7-23d9-4eaf-9644-9bbf970675cd.png)

I've added the lib folder to the PATH like the front page suggested, but to no avail. What else can I do to fix this?

**Comment by utelle** [comment]
> hey there, I'm having trouble compiling under Visual Studio 2022. It keeps telling me the following file not found error: ![image](https://user-images.githubusercontent.com/26832022/167280636-421fbec7-23d9-4eaf-9644-9bbf970675cd.png)

This clearly indicates that the compile environment is not set up properly, so that wxWidgets' include files can't be found. Assuming that you use the build files coming with wxSQLite3 you will have to inspect - and most likely to adjust - the property file `wx_setup.props` located in the `build` folder. Line 6 in this file reads:

https://github.com/utelle/wxsqlite3/blob/9aacd2c6780ff9b546da46fde39a3d65ab1a0594/build/wx_setup.props#L6

That is, the root folder of wxWidgets has to be specified. Here this is done via the environment variable `WXWIN`. Either set up this environment variable accordingly or replace `$(WXWIN)` by the absolute path to your wxWidgets installation.

Depending on how you installed wxWidgets further adjustments may be required. For example, the default compiler prefix will be simply `vc`, if you compiled wxWidgets yourself.

> I've added the lib folder to the PATH like the front page suggested, but to no avail.

The `PATH` environment variable only affects the runtime environment, not the compile time environment.

> What else can I do to fix this?

Adjusting the property file `wx_setup.props` should solve the problem.

**Comment by utelle** [comment]
Commit ca0f42975011c87c6a762d7c2b35a6ccb3586fcf adds some documentation about `wx_setup.props` to the readme file. HTH.

**Comment by Qriist** [comment]
Thanks, those suggestions got it to compile!

**Comment by utelle** [comment]
I suppose the issue can be closed then.
