### ISSUE TITLE
compile error on gcc 5.4

### ISSUE THREAD

**Issue by ILikeIneine** [utelle/wxsqlite3#106]
## pre-condition
cmake version 3.24
gcc version 5.4.0

## info
> [1] -Werror no option -Wstringop-overflow

I comment `CMakeLists.txt` line **_172_** out and it fixed

> [2] /usr/bin/ld: libwxsqlite3.a(sqlite3secure.c.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'

it failed in linking treeview, but I think it's ok? I only need libwxsqlite3.a...

**Comment by utelle** [comment]
In the meantime I did a quick check. First, I have to admit that I seldom use CMake. Second, I would like to know on which platform you are using wxSQLite3.

Actually, I was shocked by the large number of warning messages issued on compiling the SQLite code. IMHO the options used in `CMakeLists.txt` are way too pedantic. I would recommend to set the CMake option `PEDANTIC_COMPILER_FLAGS` to `OFF` (reducing the number of warnings considerably and allowing me to compile wxSQLite3 and its samples successfully). This should already fix the first issue (which is probably mainly related to the used gcc version - I have a newer version installed on my system that doesn't complain about the option ` -Wstringop-overflow`).

Regarding the second reported problem, I just noticed that you seem to use an outdated version of wxSQLite3, that is, a version below 4.6.0 (released in August 2020). Back then the encryption extension was replaced by a new implementation. I will no longer support the previous implementation.

Most likely it will be necessary to rework the CMake support completely. Since I don't have much experience with CMake, this is unfortunately a task with low priority.

**Comment by ILikeIneine** [comment]
> I would like to know on which platform you are using wxSQLite3.

on a costomized linux system base on debian. I don't know much about it. But I develop on ubuntu 16.04 with gcc 5.4.0

>  I just noticed that you seem to use an outdated version of wxSQLite3

yeah, I used the version 4.5.1 of wxSQLite3 to support the old version of sqlite3 in a project, sorry for not mention it:(

> Most likely it will be necessary to rework the CMake support completely. Since I don't have much experience with CMake, this is unfortunately a task with low priority.

It's ok, coz I've already successfully compiled it and all test cases passed! Thanks for supporting!

**Comment by utelle** [comment]
> > ... on which platform you are using wxSQLite3.
> 
> on a customized linux system base on debian. I don't know much about it. But I develop on ubuntu 16.04 with gcc 5.4.0

I don't know which version of gcc introduced option `-Wstringop-overflow`, but at least gcc 5.4.0 does not support it. IMHO this is an argument for not using too specific options in generic build files like those for CMake.

> > I just noticed that you seem to use an outdated version of wxSQLite3
> 
> yeah, I used the version 4.5.1 of wxSQLite3 to support the old version of sqlite3 in a project, sorry for not mention it:(

No problem. There are quite a few users out there using even more outdated versions. Actually, the wxSQLite3 wrapper itself didn't change much over time. That is, if you don't need newer SQLite features there is (almost) no harm in using an older wxSQLite3 version.

> > Most likely it will be necessary to rework the CMake support completely. Since I don't have much experience with CMake, this is unfortunately a task with low priority.
> 
> It's ok, coz I've already successfully compiled it and all test cases passed!

Good news. Nevertheless I will try to work on better CMake support in the future. However, no promise when it will be publicly available.
