### ISSUE TITLE
What does it mean when Mac M1 compiles this error?

### ISSUE THREAD

**Issue by jlynet** [utelle/wxsqlite3#116]
error: always_inline function '_mm_aesdeclast_si128' requires target feature 'aes', but would be inlined into function 'aesDecryptCBC' that is compiled without support for 'aes'

**Comment by utelle** [comment]
> error: always_inline function '_mm_aesdeclast_si128' requires target feature 'aes', but would be inlined into function 'aesDecryptCBC' that is compiled without support for 'aes'

Some compilers need extra compile time flags to successfully compile AES hardware support into an application.

Try to use the following compiler options `-msse4.2 -maes` on invoking the compiler. This should solve the issue.

Alternatively you can turn off AES hardware support by defining the compile time symbol `SQLITE3MC_OMIT_AES_HARDWARE_SUPPORT=1`. However, this is usually not what you want, because it slows down encryption considerably.

**Comment by utelle** [comment]
The code now uses compiler attributes, so that using the compiler options `-msse4.2 -maes` should no longer be necessary.
