### ISSUE TITLE
How to support tokenizer icu?

### ISSUE THREAD

**Issue by ejzhang** [utelle/wxsqlite3#15]
Is the precompile version support tokenizer icu? if it's doesn't supportl icu, howto compile with icu? thanks very much!

**Comment by utelle** [comment]
ICU support is not enabled in the precompiled versions of the SQLite DLL.

However, it shouldn't be too difficult to add ICU support, since ICU support is included in the SQLite amalgamation source code. So, it should be sufficient to add the definition of the symbol `SQLITE_ENABLE_ICU` for the compilation of the SQLite library. Additionally, you have to add references to the ICU link libraries, of course.

Pre-generated build files are only provided for the `wxSQLite3` library, but the `premake5` configuration file is provided for the stand-alone SQLite library. So, you could generate a build file using `premake5`.

**Comment by utelle** [comment]
The archives with pre-compiled versions for Windows now contain SQLite3 DLL and shell tool versions with enabled ICU support (see [latest release](https://github.com/utelle/wxsqlite3/releases/latest)). However, the required ICU DLLs are not included, but have to be downloaded for example from [here](http://www.npcglib.org/~stathis/blog/precompiled-icu). Alternatively, you can build them yourself, of course.
