### ISSUE TITLE
PVS Studio warnings for rijndael.c

### ISSUE THREAD

**Issue by Adriatic1** [utelle/wxsqlite3#17]
PVS reported these warnings for rijndael.c file:
rijndael.c	1103	warn	V756 The 'i' counter is not used inside a nested loop. Consider inspecting usage of 'k' counter.
rijndael.c	1256	warn	V756 The 'i' counter is not used inside a nested loop. Consider inspecting usage of 'k' counter.

Not sure how to fix this, but the loop does look strange (as if outer loop was meant to progress through multiple blocks but it does not do anything).
Could be false warning though.

BR,
  Miroslav

**Comment by utelle** [comment]
Yes, indeed the code looks strange, and most likely it wouldn't work as is. However, only the cipher mode CFB is affected. Since the SQLite3 encryption extension uses the cipher mode CBC only, the encryption extension is **_not_** affected. Nevertheless, I will try to adjust the code for a future version.

**Comment by utelle** [comment]
The code for cipher mode CFB1 is now adjusted, in case someone wants to use it in his own application.

I'd like to repeat that this wasn't an issue for the SQLite3 encryption extension, since it is based on cipher mode CBC.
