### ISSUE TITLE
sqlite3.c:375:21: error: expected value in expression #if SQLITE_HAS_CODEC

### ISSUE THREAD

**Issue by iamcxl369** [utelle/wxsqlite3#19]
I got some error after define the SQLITE_HAS_CODEC
```
sqlite3.c:375:21: error: expected value in expression
#if SQLITE_HAS_CODEC
```
```
#if SQLITE_HAS_CODEC should change to #if defined(SQLITE_HAS_CODEC)
```

**Comment by utelle** [comment]
Thanks for reporting.  Interestingly, I don't get even a warning when I compile SQLite with Visual C++. Otherwise I would certainly have detected the issue myself.

Obviously the SQLite project checks inconsistently for an enabled encryption option (SQLITE_HAS_CODEC) - in file `sqlite.c` I found 23 times `#ifdef SQLITE_HAS_CODEC`, but also 5 times `#if SQLITE_HAS_CODEC`.

I will not start to manually adjust the SQLite source code. Therefore I will change the preprocessor symbol definition to `SQLITE_HAS_CODEC=1` to overcome the issue.

**Comment by utelle** [comment]
The build files coming with wxSQLite3 have been adjusted to use the symbol definition `SQLITE_HAS_CODEC=1`.

I reported the inconsistent use of the symbol in the SQLite source code on the SQLite mailing list, but I don't know if and when the SQLite code will be adjusted. Therefore I recommend to use the above shown symbol definition in own projects to avoid problems.
