### ISSUE TITLE
legacy_page_size isn't documented

### ISSUE THREAD

**Issue by emkey08** [utelle/wxsqlite3#39]
The `legacy_page_size` parameter isn't explicitly [documented](https://github.com/utelle/wxsqlite3/tree/master/sqlite3secure) (but only used within the examples).

**Comment by utelle** [comment]
Well, the new feature for selecting the encryption cipher at runtime is work in progress.

I added this parameter, `legacy_page_size`, to all ciphers, because especially for the legacy versions of the ciphers **sqleet** and **SQLCipher** it is usually required to explicitly set the database page size, since SQLite can't detect it from the database header and will use the default page size, which might not be the correct one.

Version 3.12.0 of SQLite changed the default page size from 1024 to 4096 bytes. However, for example SQLCipher still uses a page size of 1024 bytes, even for newer versions of SQLite. If the page size is not set explicitly, opening a database encrypted with legacy SQLCipher will fail.

For a user/developer it is cumbersome to remember to issue a `PRAGMA page_size` at the right time. Therefore the wxSQLite3 encryption extension has now the parameter `legacy_page_size` which allows to automatically set the page size in legacy mode of a cipher.

Not explicitly documenting this new parameter was simply an oversight.

**Comment by utelle** [comment]
Commit 94ec6efb6199374b924608faeaa99705cea7756f merged the updated documentation. Thanks to @emkey08.
