### ISSUE TITLE
config.gcc should not specify compiler version number - breaks wxwidgets lib paths

### ISSUE THREAD

**Issue by ouch67** [utelle/wxsqlite3#40]
The variable wxCompilerPrefix in config.gcc specifies the compiler version number but really shouldn't as the makefiles use it to determine the path to wxWidgets libs.
so:

wxCompilerPrefix ?= gcc720

results in paths like:

wxWidgets/lib/gcc720_dll/mswu
wxWidgets/lib/gcc720_lib/mswu

should default to:

wxCompilerPrefix ?= gcc

to produce paths like:

wxWidgets/lib/gcc_dll/mswu
wxWidgets/lib/gcc_lib/mswu

**Comment by utelle** [comment]
Since I mostly develop under Windows using Visual C++, I usually test mingw only based on the precompiled wxWidgets binaries available from the wxWidgets website. For (one of) the available set of precompiled libraries the prefix as given in `config.gcc` is the correct one.

No excuse, but an explanation why `config.gcc` has the compiler prefix `gcc720`. (For some previous releases it was `gcc510TDM`.) Probably I should mention this in the readme file.

Maybe the compiler prefix should be set to `gcc`, since it is the default when building wxWidgets yourself. However, as a developer you will have to check the settings in `config.gcc` anyway, so that they match your own installation.

**Comment by utelle** [comment]
Commit 538ac7f573d59e59fd20443e13a8b7a5782d77e6 fixes this issue.
