### ISSUE TITLE
Cannot build static sqlite3secure shell

### ISSUE THREAD

**Issue by kivadiu** [utelle/wxsqlite3#43]
If I try to build sqlite3secure with `configure --disable-shared --enable-static` (on linux x86_64), I get the following error while linking:
```
./.libs/libsqlite3secure.a(sqlite3secure.o): In function `sqlite3_shathree_init':
/home/fred/Devel/Git/wxsqlite3/sqlite3secure/src/shathree.c:697: multiple definition of `sqlite3_shathree_init'
src/shell.o:/home/fred/Devel/Git/wxsqlite3/sqlite3secure/src/shell.c:2009: first defined here
./.libs/libsqlite3secure.a(sqlite3secure.o): In function `sqlite3_fileio_init':
/home/fred/Devel/Git/wxsqlite3/sqlite3secure/src/fileio.c:908: multiple definition of `sqlite3_fileio_init'
src/shell.o:/home/fred/Devel/Git/wxsqlite3/sqlite3secure/src/shell.c:2938: first defined here
```

I guess it works with the dynamic library because the one of shell.c is hard linked.
How do you create the files from the official sqlite3 3.24.0?

**Comment by utelle** [comment]
Thanks for reporting the issue.

The problem is that the shell source code (`shell.c`) itself includes the source code of the `SHA3` and `fileio` extensions. Therefore in this case the SQLite3 library should be compiled without those extensions to avoid doubly defined functions.

The build files for Windows take care of this issue, but `makefile.am` does not unfortunately, I have to admit.

I'll try to provide an adjusted `makefile.am` soon.

**Comment by kivadiu** [comment]
Thank you, this helped me a lot to fix my own Makefile (I do not normally use configure for sqlite).

**Comment by utelle** [comment]
With `#define CODEC_TYPE CODEC_TYPE_xxx` you select codec type `xxx`as the default cipher. However, any of the supported ciphers can also be selected at runtime. Further information can be found [here](https://github.com/utelle/wxsqlite3/tree/master/sqlite3secure).

**Comment by kivadiu** [comment]
Excellent, thanks for the excellent documentation I did not find myself.

**Comment by utelle** [comment]
In the meantime I investigated a bit further the original issue.

As you observed there doesn't seem to be a problem if a shared library is built and used by the SQLite3 `shell`. However, for a static built a differently compiled SQLite3 library would be required (excluding the `sha3` and `fileio` extensions), because the source inclusion of these extensions in `shell.c` can't be deactivated easily. IMHO it doesn't make much sense to build 2 different library versions.

One option to overcome this problem would be to always include the SQLite3 library statically in the SQLite3 shell. In fact, this is the way it is done under Windows, because it ensures that the SQLite3 shell does not depend on the accessibility of a shared SQLite3 library.

If no one objects, I would use the same approach for the Linux build.

**Comment by kivadiu** [comment]
Seems the good approach to me.

**Comment by utelle** [comment]
I adjusted `Makefile.am` accordingly. Commit 0d1189cb1ac09aae2aab3c5cc27e6a4bd03ef306 fixes the issue.

**Comment by kivadiu** [comment]
Thanks, it works now.
