### ISSUE TITLE
Compiling wxsqlite3-4.4.3

### ISSUE THREAD

**Issue by Carluccio** [utelle/wxsqlite3#52]
Errors in the wxsqlite3.cpp file compiled with TDM-GCC-64 and wxWidgets-3.1.2.
Is TDM-GCC-64 compatible?
regards,
Sala Carlo

**Comment by utelle** [comment]
Since **TDM-GCC** is rather dated, I usually test wxSQLite3 only using **mingw-w64** - main development is based on **Visual C++**. Therefore I currently don't know whether there are issues using **TDM-GCC**.

Could you please give some more details about the errors you experience? Do you get errors compiling the wrapper (`wxsqlite3.cpp`) or on compiling the encryption extension (`sqlite3secure.c`)?

**Comment by Carluccio** [comment]
The errors are numerous, I'll try again with mingw-w64 also recompiling wxWidgets-3.1.2 with that.
I get errors only in the wrapper (wxsqlite3.cpp)
regards
Carlo Sala

**Comment by Carluccio** [comment]
With MinGw64, everything goes well. but with tdm-ggc 64 version 5.1.0, I get the following errors that I point out in the attachment (errors.txt)
regards
Carlo Sala
[errors.txt](https://github.com/utelle/wxsqlite3/files/3236730/errors.txt)

**Comment by utelle** [comment]
Looking at the provided error log I get the impression that you somehow mixed up different **wxSQLite3** versions.

It seems you copied some **wxSQLite3** header files to your **wxWidgets** include directory, namely `D:\wxWidgets-3.1.2/include/wx/wxsqlite3.h`. My guess is that that header file belongs to an older, pre-4.0.0 version of **wxSQLite3**., while your source file `../src/wxsqlite3.cpp` belongs to a 4.x version of **wxSQLite3**.

1) You shouldn't copy the header files of **wxSQLite3** to the **wxWidgets** include directory.
2) You mustn't mix up **wxSQLite3** versions. To compile **wxSQLite3** successfully, you need to reference the matching header file(s).

That is, your problem is most likely not related to the compiler version, but to the source code set up.

**Comment by Carluccio** [comment]
Yes it is true, what a fool I was!
I try with a clean wxWidgets version from the files of the previous version of wxsqlite3
sorry for the inconvenience greetings
Carlo Sala

**Comment by utelle** [comment]
I guess it is ok to close this issue for now. Reopen it, in case you still experience problems after cleaning up your source tree.
