### ISSUE TITLE
VCRUNTIME140.dll missing on Windows 10 / 64bit

### ISSUE THREAD

**Issue by lazna** [utelle/wxsqlite3#54]
Get error message when starting  on W10/64bit. MICROSOFT VISUAL STUDIO 2015 REDITRIBUTABLE installed and reinstalled few times, all older releases of MSVC uninstalled before. What Can I did more?

**Comment by utelle** [comment]
First of all your error description is very vague, unfortunately. Which application did you start? What exactly are you trying to accomplish?

If `VCRUNTIME140.dll` is missing, this usually indicates that the VC++ 2015 runtime is not properly installed on your system. You should download the [Visual C++ 2015 Redistributable(s)](https://www.microsoft.com/en-us/download/details.aspx?id=52685) and install it/them. Maybe you will have to reboot your computer thereafter.

**Note**: The redistributable comes in 2 flavors: _vcredist_x64.exe_ and _vcredist_x86.exe_. You need the former for 64-bit applications and the latter for 32-bit applications. If you have _64-bit **and** 32-bit_ applications, you should install both runtime versions.

**Comment by lazna** [comment]
traying start sqlite3shellicu.exe from cmdline, got doubleGUI errormessage the file VCRUNTIME140.dll missing. What more info you need?

**Comment by utelle** [comment]
The SQLite shell binaries provided with a **wxSQLite3** release also come in 2 flavors: 64-bit and 32-bit. `sqlite3shellicu.exe` is a 32-bit binary. Start `sqlite3shellicu_x64.exe` if you intend to use the 64-bit variant.

Since you started the 32-bit SQLite shell with ICU support you'll have to install the 32-bit variant of the VC++ runtime (i.e. _vcredist_x86.exe_), not the 64-bit variant.

**Comment by utelle** [comment]
IMHO this problem has nothing to do with wxSQLite3 itself. It looks like a misconfiguration of the installed VC++ runtime (which is only required by ICU in this case). Therefore I'm closing the issue.
