### ISSUE TITLE
How to open a db encrypted by Navicat.

### ISSUE THREAD

**Issue by netsesame2** [utelle/wxsqlite3#57]
I've a sqlite db, encrypted by Navicat for Sqlite.
However, I don't know how to open it in wxsqlite3's open function.

Please help.

**Comment by utelle** [comment]
According to the [Navicat documentation](https://help.navicat.com/hc/en-us/articles/217791188-What-SQLite-database-encryption-method-does-Navicat-support-) the default encryption method used by Navicat is **wxSQLite3 AES 128-Bit** - the default scheme used by wxSQLite3 up to version 3.5.9. The default wxSQLite3 encryption scheme was changed in version 4.0.0 to **ChaCha20**; that is, if you use a recent version of the wxSQLite3 encryption extension (compiled with default settings) you have to explicitly specify the cipher scheme. I.e., use the `cipher` URI parameter when specifying the database file name:
```
'file:your_navicat_database_file.db?cipher=aes128cbc'
```
Of course, you also have to specify the correct password (`key=` URI parameter or `PRAGMA key=` SQL command, or key parameter of the `Open` method of the `wxSQLite3Database` class) to successfully open your Navicat database file.

If you use the wxSQLite3 wxWidgets wrapper classes, you may pass a `wxSQLite3CipherAes128` class instance to the `Open` method instead of using the `cipher` URI parameter.

However, Navicat also supports to exchange its SQLite DLL, thus to change the supported encryption method(s). If your Navicat database file was not created using the default encryption method (wxSQLite3 AES 128-Bit), then you will have to find out first, which encryption scheme was used and whether it is an encryption scheme supported by wxSQLite3.

**Comment by netsesame2** [comment]
Thanks much. It's resolved.

**Comment by utelle** [comment]
Sure, setting a different compile time default is also an option. It depends on the actual needs what's the most convenient solution.
