### ISSUE TITLE
Sqlcipher support

### ISSUE THREAD

**Issue by guanlisheng** [utelle/wxsqlite3#6]
as well known that Sqlcipher is a more popular SQLite extension that provides 256 bit AES encryption of database files. i am wondering whether there is a plan to support it.

Thanks

**Comment by utelle** [comment]
The encryption extension coming with wxSQLite3 can be configured to use 256 bit AES encryption instead of the default 128 bit AES encryption.

Besides that you are free to combine the SQLCipher SQLite library with wxSQLite3. wxSQLite3 should work with SQLCipher out of the box, since SQLCipher uses the official encryption interface (`sqlite3_key` and `sqlite3_rekey`). This requires just to link wxSQLite3 against the SQLCipher library - any reasonably experienced developer should be able to do this.

IMHO no modifications to the wxSQLite3 source code are required to use the SQLCipher based SQLite library. So what would you expect from a SQLCipher support for wxSQLite3? How would it look like?

**Comment by utelle** [comment]
Since it was not clarified what would be expected from SQLCipher support for wxSQLite3, I close this issue. Feel free to reopen it, if additional information is provided.

**Comment by guanlisheng** [comment]
with the following pragma, wxsqlite3 can open sqlcipher's file
```
PRAGMA cipher=SQLCipher;
pragma legacy=4;
```

**Comment by utelle** [comment]
> with the following pragma, wxsqlite3 can open sqlcipher's file
> 
> ```
> PRAGMA cipher=SQLCipher;
> pragma legacy=4;
> ```

**wxSQLite3** has support for **SQLCipher** for almost 5 years now, using the class [`wxSQLite3CipherSQLCipher`](https://utelle.github.io/wxsqlite3/docs/html/classwx_s_q_lite3_cipher_s_q_l_cipher.html) as a parameter to the `wxSQLite3Database::Open` method (if you are using it in a wxWidgets based application) - see the `minimal` sample coming with **wxSQLite3** for an example.

Of course, it is possible to configure the cipher scheme **without** using the class [`wxSQLite3CipherSQLCipher`](https://utelle.github.io/wxsqlite3/docs/html/classwx_s_q_lite3_cipher_s_q_l_cipher.html) by using `PRAGMA` SQL statements or even by using URI parameters with the database file name - that is, with **all** methods described in the [SQLite3 Multiple Ciphers documentation](https://utelle.github.io/SQLite3MultipleCiphers/docs/configuration/config_overview/). But IMHO in a **wxSQLite3** based application using a dedicated `wxSQLite3Cipher` classes is usually more convenient.

**Comment by guanlisheng** [comment]
agreed. 
Currently, the case is to migrate from `aes128cbs` to `SQLCipher` gradually for both the program and its data.

**Comment by utelle** [comment]
> Currently, the case is to migrate from `aes128cbs` to `SQLCipher` gradually for both the program and its data.

Method
```C++
wxSQLite3Database::ReKey(const wxSQLite3Cipher &cipher, const wxString &newKey)
```
can be used to not only change the passphrase, but also the cipher scheme - just pass an appropriately initialized  `wxSQLite3Cipher` object as the first parameter.

The only constraint is that enough disk space is available to actually do the conversion - free disk space of about 2 times the current size of the database should usually be enough.

And of course the application needs _exclusive_ access to the database file.
