### ISSUE TITLE
noexcept overloads for some simple frequently used functions

### ISSUE THREAD

**Issue by Deamhan** [utelle/wxsqlite3#65]
I think it would be great to add such functions if compiler support noexcept statement (or throw() if it does not). Check can be done through cmake feature checking (or manual adding to project files and checking compiler feature/version in makefile) and defining special macroses. If you don't mind I will do such thing.

**Comment by utelle** [comment]
1) I don't want to introduce a hard dependency on CMake.
2) I don't want to have to manually modify project files, because this makes maintaining them difficult.
3) I don't want to clutter the code with macros, although I know that some other libraries chose that approach.

If and when I decide to upgrade the code base of wxSQLite3 to a more recent C++ standard, the `noexcept` keyword may then be applied if appropriate. For such an upgraded version I don't see a necessity to introduce additional noexcept overloads.

**Comment by Deamhan** [comment]
I don't suggest hard dependency on CMake or modify project files - just checking macro values. About macros... such thing can't be done without it... I understand your point of view, may be it is right decision (I don't like macro too)

**Comment by utelle** [comment]
Currently the wxSQlite3 code is already cluttered with macros, since in the beginning I didn't bundle the SQLite source code with wxSQLite3. And many new SQLite versions added features and functions to the API. Additionally, I had to support different versions of wxWidgets due to project requirements.

Now, that the SQLite source code is bundled with wxSQLite3 it is technically no longer necessary to check for certain SQLite versions.

I intend to clean up the wxSQLite3 code in the future, but as usual I have to find enough spare time to dedicate to this task.
