### ISSUE TITLE
Can't create statically linked apps (Windows 10 and VS2019 Community Edition)

### ISSUE THREAD

**Issue by ga2k** [utelle/wxsqlite3#73]
I would appreciate some help with this issue, which I have been having since my last issue request in September 2018.

DLL builds of my app (and Minimal and Treeview) work fine. Statically linking my app (or Minimal/Treeview) has TONS of link errors (see attached list for the error list from a build attempt of DEBUG x64)

[Errors.txt](https://github.com/utelle/wxsqlite3/files/3464851/Errors.txt)

I have been using DLL builds to avoid this issue, but it is really bugging me that I can't build statically linked apps.

Any help with configuration would be greatly appreciated.

**Comment by utelle** [comment]
Obviously there is a mixup of static and shared builds/libs in your project. For further analysis more information is required. 

How did you build the wxSQLite3 library? Did you use the project files coming with wxSQLite3? If yes, which configuration did you choose?

Additionally, please provide the compiler and linker options used for building your project.

The build files coming with wxSQLite3 for the samples should work right out of the box, if you have a properly built wxWidgets version, and build file `build\wx_setup.props` was adjusted to point to your wxWidgets installation (i.e. property `wxRootDir` is set correctly).

**Comment by ga2k** [comment]
Steps to reproduce 

Download and extract wxWidgets to D:\wxWidgets. Make no changes whatsoever.
[DIR_wxWidgets.txt](https://github.com/utelle/wxsqlite3/files/3466111/DIR_wxWidgets.txt)

set WXWIN=D:\wxWidgets in Control Panel
set WXROOTDIR=D:\wxWidgets in Control Panel
Verify by opening new Cmd Prompt and typing SET W
[SET_w.txt](https://github.com/utelle/wxsqlite3/files/3466114/SET_w.txt)

Open NEW copy of Windows Explorer (to pick up new environment)
Double Click  **D:\wxWidgets\build\msw\wx_vc15.sln**

Visual Studio 2019 Community Edition starts and prompts me to upgrade solution to latest compiler toolset. I do this.

Rebuild entire solution by Build/Batch Build/Select All+Build
========== Build: 192 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

Download and extract wxSQLite3 to D:\wxSQLite3-master. Make no changes whatsoever.
[DIR_wxSQLite3-Master.txt](https://github.com/utelle/wxsqlite3/files/3466168/DIR_wxSQLite3-Master.txt)

Open D:\wxsqlite3-master\build\wxsqlite3_vc15.sln

Visual Studio 2019 Community Edition prompts me to upgrade solution to latest compiler toolset. I do this.

Rebuild entire solution by Build/Batch Build/Select All+Build
========== Build: 28 succeeded, 8 failed, 0 up-to-date, 0 skipped ==========
[BuildOutput.txt](https://github.com/utelle/wxsqlite3/files/3466188/BuildOutput.txt)

Many failures, only in Static Link projects.

Is there somewhere else I should look for "hidden" configuration files that might be stuffing things up?

Cheers.

**Comment by utelle** [comment]
I now know what's going on. The problem is a deficiency of the build files coming with wxSQLite3. For wxWidgets itself you typically have 2 main configurations: static and shared, and the resulting libraries are stored in `lib/vc_lib` resp `lib/vc_dll`. However, wxSQLite3 supports 3 main configurations:

1. static wxSQLite3 + static wxWidgets
2. static wxSQLite3 + shared wxWidgets
3. shared wxSQLite3 + shared wxWidgets

The problem is that currently libraries resulting from1) and 2) are both saved in the same location, `lib/vc_lib`, under the same library name. That is, you can't have both configurations at the same time.

Instead of building **all** configurations for wxSQLite3 you should build only those which you really need.

I will try to adjust the build files for the next release, so that **build all** will work. However, I'm a bit undecided how to do it. I can either store the library in a different location or give it a different name. Most likeley I will prefer to create an additional subdirectory for the library.

**Comment by utelle** [comment]
Commit ae81e858ad95699a9e4c8df458d018759fbf8795 should fix the issue.

**Comment by ga2k** [comment]
Excellent. 

⁣Get BlueMail for Android ​

**Comment by utelle** [comment]
Commit 62cfb3335608a43fe56433557cdc1fe01134084a adds the build files for VS2019 that were unfortunately missing from the previous commit.

Please reopen the issue if necessary.

**Comment by ga2k** [comment]
New update works perfectly. Thanks.
