### ISSUE TITLE
Build error for wxSQLite3 4.4.6 (VS2019)

### ISSUE THREAD

**Issue by Kvaz1r** [utelle/wxsqlite3#78]
I get build error for release 4.4.6(for master branch too): 
> ...\wxWidgets-3.1.2\include\msvc\wx\setup.h(125,10): error C1083:  Не удается открыть файл включение: ../../../lib/vc141_lib/mswu/wx/setup.h: No such file or directory,

release 4.4.5 build as expected. Was there introduced some more steps which required for building?

**Comment by utelle** [comment]
Probably I should have made a note somewhere that I modified the property file `wx_setup.props` in the `build` subdirectory. This was necessary to allow running AppVeyor CI without any modifications.

This modification triggers the use of specific library directories for different compiler versions (as it is used by the pre-built wxWidgets libraries). This adds the toolkit version (141 for VS 2015, 142 for VS 2019) to the library path name.

Additionally, there is a problem with the wxWidgets 3.1.2 release, because it doesn't support VS 2019 in this mode yet. The file [include/msvc/wx/setup.h](https://github.com/wxWidgets/wxWidgets/blob/master/include/msvc/wx/setup.h) has been updated (lines 68 to 71) in the GitHub repository, but the released version selects the wrong toolkit version (the one belonging to VS 2015).

To get the previous behaviour (library path names without toolkit version) please adjust the 2 parameters _wxCompilerPrefix_ and _wxMsvcVersionAuto_ as follows:
```xml
<wxCompilerPrefix>vc</wxCompilerPrefix>
<wxMsvcVersionAuto></wxMsvcVersionAuto>
```
Sorry for the inconvenience.

**Comment by Kvaz1r** [comment]
Yes, thank you, it works if also set wxMsvcVersionAuto to empty:

`<wxMsvcVersionAuto></wxMsvcVersionAuto>`
