### ISSUE TITLE
Release windows zip files missing include files

### ISSUE THREAD

**Issue by acotty** [utelle/wxsqlite3#83]
The release Windows *.zip files do not contain the include files from the /include/wx directory that are also needed if you want to just use libs/dll's in the zip file.

Sorry I do not have enough time to investigate how the packages are generated and supply a patch as I am trying to build a package that uses wxsqlite3.

**Comment by utelle** [comment]
> The release Windows *.zip files do not contain the include files from the /include/wx directory

That is true, but those files are not needed, because the Windows binaries ZIP files contain only a precompiled SQLite3 shell and precompiled SQLite3 DLLs with encryption support. _Precompiled versions of the wxWidgets based wxSQLite3 library are **not** included._

> that are also needed if you want to just use libs/dll's in the zip file.

No, the header files located in `include/wx` are not needed, because the wxWidgets based wxSQLite3 library has always to be compiled from sources. However, it certainly would make sense to include the header files from `sqlite3secure/src` which are required for using the precompiled DLLs. And I will do so starting with the next release.

**Comment by utelle** [comment]
A new implementation of the SQLite encryption extension is now available as a separate project: [SQLite3 Multiple Ciphers](https://github.com/utelle/SQLite3MultipleCiphers). The binaries of the [first release](https://github.com/utelle/SQLite3MultipleCiphers/releases/tag/v1.0.0) now contain the C header files as well.
