### ISSUE TITLE
Rekey issue

### ISSUE THREAD

**Issue by yzhgu** [utelle/wxsqlite3#91]
I saw sqlite3_rekey() is called to set the db password. In api function sqlite3_rekey(), the PageSize is checked to make sure that Pagesize cannot be changed for an encrypted database.
```
if (nPagesizeWriteCipher <= 0 || nPagesize == nPagesizeWriteCipher)
{...}
```
How about if I want to encrypt a normal db (not encrypted one) using sqlcipher with different pagesize from that of original db? I was not able to set the db password then. I think in this case sqlite3_key() should be called instead of sqlite3_rekey().
Am I right? or Did I miss something?

**Comment by utelle** [comment]
Function `sqlite3_key()` is used to set the encryption passphrase for existing already encrypted databases or newly created empty databases. Function `sqlite3_rekey()` is used to change the passphrase of an already encrypted database or to set the passphrase and to encrypt an unencrypted database.

Due to internal limitations of SQLite, the function `sqlite3_rekey()` can't change the page size of a database. That is, you have to adjust the page size **before** encrypting the database using the following steps on an _unencrypted_ database:

```SQL
PRAGMA page_size=8192; -- Request the page size you want
VACUUM; -- Apply the new page size
PRAGMA cipher='sqlcipher'; -- Select cipher scheme, if not default
PRAGMA rekey='passphrase';
```
As described in the documentation of [PRAGMA page_size](https://www.sqlite.org/pragma.html#pragma_page_size) the database must not be in WAL mode.

If you want to create a database which is compatible with the original SQLCipher library, you have to keep in mind that you have to set the legacy mode as well.

**Comment by yzhgu** [comment]
Thk a lot for the help
