### ISSUE TITLE
How to access wxsqlite3 encrypted database in Android。there is already a key

### ISSUE THREAD

**Issue by ltym2016** [utelle/wxsqlite3#96]

**Comment by utelle** [comment]
Your question is too unspecific. You have to provide more details of what exactly you are trying to accomplish.

Are you transferring an already encrypted database file to an Android system? Or was the encrypted database file created on an Android system? If the latter, which encryption scheme was used to create the database file?

Since _wxSQLite3_ 4.6.0 (released in August 2020) the encryption extension is based on the separate encryption extension [SQLite3 Multiple Ciphers](https://github.com/utelle/SQLite3MultipleCiphers). Which _wxSQLite_ resp _SQLite3 Multiple Ciphers_ version are you using? Which encryption scheme are you using?

_wxSQLite3_ resp _SQLite3 Multiple Ciphers_ do not provide out-of-the-box support for Android. However, the [SQLite Android Bindings](https://www.sqlite.org/android/doc/trunk/www/index.wiki) project provides an easy way to bundle a custom SQLite3 version into an Android application with the standard Android interface [android.database.sqlite](https://developer.android.com/reference/android/database/sqlite/package-summary).

**Comment by utelle** [comment]
Since you did not provide any further information, I suppose that your problem is solved. Therefore I'm closing this issue. Feel free to re-open it if necessary.
